apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: english-service-monitor
  # namespace: default 
  labels:
    app: "english-greeter"
spec:
  jobLabel: english-app
  selector:
    matchLabels: 
      app: english-greeter
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s
    