apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: planetarium-service-monitor
  # namespace: default 
  labels:
    app: "planetarium"
spec:
  jobLabel: planetarium-app
  selector:
    matchLabels: 
      app: planetarium
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s
    